### ISSUE TITLE
Compatibility issues due to system changes?

### ISSUE THREAD

**Issue by 64BTX** [lskyset/priconne-asset-extractor#9]
I wanted to use this again after a while, but I'm getting this error now despite having all the required stuff. It properly gets the manifest_assetmanifest, but then it shows this:

![pic](https://github.com/lskyset/priconne-asset-extractor/assets/47084488/8130804f-23d7-4af4-8d6d-ad254b3d9e6d)

I know there were some in-game engine and system changes over the past few months (I think it could've potentially changed the database formatting in some capacity), so maybe that was the cause? If it helps, the program worked fine when I used it in October of last year.

**Comment by AbadiOK** [comment]
i also have the same Problem
![error Priconne Lskyset_2](https://github.com/lskyset/priconne-asset-extractor/assets/124959802/11df30b5-8cd9-491c-a34f-dff2a4171e70)

**Comment by 64BTX** [comment]
Found a fix! See https://github.com/lskyset/priconne-asset-extractor/pull/10
I guess Priconne added a new entry in the manifests sometime recently.

**Comment by 64BTX** [comment]
Found a new error now, this time it's when trying to extract asset bundles directed by certain asset manifests (it's happened with 'howtoplay2' and 'atlasngui2' for me so far, there could be more):
![pic0](https://github.com/lskyset/priconne-asset-extractor/assets/47084488/fcae5310-fe40-49a4-af76-d95266845f2c)
It downloads the .unity3d asset bundles fine, but it throws the error when actually trying to extract things from them. Asset bundles from other manifests seem to get extracted perfectly fine.
